### ISSUE TITLE
Your issue: sending $H using LCD menu doesn't work, USB works OK

### ISSUE THREAD

**Issue by HuubBuis** [how-eee/grbl_lathe_UI_threading#1]
[Your post:](https://github.com/MetalWorkerTools/grbl-L-Mega/issues/4#issuecomment-817160017) 
> have read out almost all code. cant find difference of parsing $H sended via usb and via lcd menu. But via lcd menu I have alarm in the end of homing cycle, via usb all is ok

I remember I had such an issue using grbl_ESP32  sending commands using USB and Bluetooth was OK, using WiFi didn't work.
The cause was the line termination used.  Just a **cr or lf** didn't work. The solution was sending crlf.

**Comment by how-eee** [comment]
I have changed UImenu homing class.
